### ISSUE TITLE
Failed to load AsciiDoc document - no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/metanorma-plugin-datastruct#27]
```
/__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/source_extractor.rb:60:in `initialize': no implicit conversion of nil into String (TypeError)
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/source_extractor.rb:60:in `open'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/source_extractor.rb:60:in `read'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/source_extractor.rb:37:in `block in extract'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/source_extractor.rb:33:in `loop'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/source_extractor.rb:33:in `extract'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/source_extractor.rb:27:in `extract'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-plugin-datastruct-0.2.4/lib/metanorma/plugin/datastruct/base_structured_text_preprocessor.rb:33:in `process'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:533:in `[]'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:533:in `block in parse'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:532:in `each'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.20/lib/asciidoctor/document.rb:532:in `parse'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/asciidoctor-2.0.20/lib/asciidoctor/load.rb:84:in `load'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/input/asciidoc.rb:25:in `asciidoctor_validate'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/input/asciidoc.rb:13:in `process'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/processor.rb:21:in `input_to_isodoc'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:59:in `process_input_adoc'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:41:in `process_input'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-1.5.12/lib/metanorma/compile.rb:33:in `compile'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/compiler.rb:45:in `compile_file'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/compiler.rb:30:in `compile'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/compiler.rb:35:in `compile'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/site_generator.rb:91:in `compile'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/site_generator.rb:31:in `block in generate'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/site_generator.rb:31:in `each'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/site_generator.rb:31:in `generate'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/site_generator.rb:26:in `generate'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli/commands/site.rb:33:in `generate'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:127:in `invoke_command'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:[116](https://github.com/metanorma/rfc-asciidoc-rfc/actions/runs/6097902791/job/16546518218#step:5:124):in `invoke'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:243:in `block in subcommand'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/command.rb:27:in `run'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-hollaback-0.2.1/lib/thor/hollaback.rb:68:in `run'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/invocation.rb:[127](https://github.com/metanorma/rfc-asciidoc-rfc/actions/runs/6097902791/job/16546518218#step:5:135):in `invoke_command'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor.rb:392:in `dispatch'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/thor-1.2.2/lib/thor/base.rb:485:in `start'
	from /__tebako_memfs__/lib/ruby/gems/3.1.0/gems/metanorma-cli-1.7.6/lib/metanorma/cli.rb:34:in `start'
	from /__tebako_memfs__/local/metanorma:217:in `<main>'
```

https://github.com/metanorma/rfc-asciidoc-rfc/actions/runs/6097902791/job/16546518218

**Comment by CAMOBAP** [comment]
https://github.com/metanorma/rfc-asciidoc-rfc/ - repository removed
